name: Run Rijksmuseum Postman Collections with Newman

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the main branch

jobs:
  newman_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository containing the Postman collections, environment, and globals
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (required for Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Postman collection for each collection with English and Dutch environments
      # Run 'collection_API' collection with EN and NL environments
      - name: Run Collection API (EN Production)
        run: |
          newman run collections/collection_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-collection-EN.html

      - name: Run Collection API (NL Production)
        run: |
          newman run collections/collection_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-collection-NL.html

      # Run 'collectionDetails_API' collection with EN and NL environments
      - name: Run Collection Details API (EN Production)
        run: |
          newman run collections/collectionDetails_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-details-EN.html

      - name: Run Collection Details API (NL Production)
        run: |
          newman run collections/collectionDetails_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-details-NL.html

      # Run 'collectionTiles_API' collection with EN and NL environments
      - name: Run Collection Tiles API (EN Production)
        run: |
          newman run collections/collectionTiles_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-tiles-EN.html

      - name: Run Collection Tiles API (NL Production)
        run: |
          newman run collections/collectionTiles_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-tiles-NL.html

      # Step 5: Upload HTML reports as build artifacts
      - name: Upload Collection API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-collection-reports
          path: |
            newman-report-collection-EN.html
            newman-report-collection-NL.html

      - name: Upload Collection Details API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-details-reports
          path: |
            newman-report-details-EN.html
            newman-report-details-NL.html

      - name: Upload Collection Tiles API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-tiles-reports
          path: |
            newman-report-tiles-EN.html
            newman-report-tiles-NL.html