name: Run Rijksmuseum Postman Collections with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Newman
        run: npm install -g newman

      # Run Collection API (EN Production) and continue on error
      - name: Run Collection API (EN Production)
        run: |
          newman run collections/collection_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-collection-EN.html
        continue-on-error: true  # Allows the workflow to continue if this step fails

      # Run Collection API (NL Production) and continue on error
      - name: Run Collection API (NL Production)
        run: |
          newman run collections/collection_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-collection-NL.html
        continue-on-error: true

      # Run Collection Details API (EN Production)
      - name: Run Collection Details API (EN Production)
        run: |
          newman run collections/collectionDetails_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-details-EN.html
        continue-on-error: true

      # Run Collection Details API (NL Production)
      - name: Run Collection Details API (NL Production)
        run: |
          newman run collections/collectionDetails_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-details-NL.html
        continue-on-error: true

      # Run Collection Tiles API (EN Production)
      - name: Run Collection Tiles API (EN Production)
        run: |
          newman run collections/collectionTiles_API.collection.json \
            --environment environment/en_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-tiles-EN.html
        continue-on-error: true

      # Run Collection Tiles API (NL Production)
      - name: Run Collection Tiles API (NL Production)
        run: |
          newman run collections/collectionTiles_API.collection.json \
            --environment environment/nl_production.environment.json \
            --globals environment/globals.json \
            --reporters cli,html \
            --reporter-html-export newman-report-tiles-NL.html
        continue-on-error: true

      # Upload Collection API reports
      - name: Upload Collection API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-collection-reports
          path: |
            newman-report-collection-EN.html
            newman-report-collection-NL.html

      # Upload Collection Details API reports
      - name: Upload Collection Details API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-details-reports
          path: |
            newman-report-details-EN.html
            newman-report-details-NL.html

      # Upload Collection Tiles API reports
      - name: Upload Collection Tiles API reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-tiles-reports
          path: |
            newman-report-tiles-EN.html
            newman-report-tiles-NL.html